import type { Metadata } from "next";

// components
import { ReduxProvider, ThemeProvider } from '@/components';
import { ToastContainer } from 'react-toastify';

// css
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider> 
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
